---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1lm9yj3lcn9xy8qzwvhs0fr77vzxdzggqr3te7307dxx8eztsay4sewphmd"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1lm9yj3lcn9xy8qzwvhs0fr77vzxdzggqr3te7307dxx8eztsay4sewphmd"
