apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:9UV2kgo816ox34/6tcsVGF+F+nKRY/p01i0pgCVhC7cdLU2h,iv:nyx2YdRUotYxb4t5/ixMIKqCDzJDXuqHmAo/kqwL7T8=,tag:qxmvZsK+ChKNd9KJL3Uc2g==,type:str]
    credentials.json: ENC[AES256_GCM,data:3oZHXU6140jAf94OW0qpZl/H7rjU4htIh8LqlsdTwW4wUumBoAgPOnskgo+c94CiPYiYvexDmlWfP6HNN0BAhvBIKE6YuswyLOdmtboGZNITK2/m0Aja+5CyLVsAGbKXV/0gap1lMFlcWP7JGeZRvu6CBgVx1Odb1/yKiFB8D/E43aqCvDNzkP1bVYIDOkEL4fi3rLWNSQXosDqf0y/2cKcSBG9EnbCy0QM2CQ999A==,iv:Wxfaz+1Q6hV4ctbr8ZS+sDpJ5FRN6HZDc8+nwi3ATKo=,tag:k/u2AtksQ/ACwNFCE3CHpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zeeh6dv2dnu0de6xd2zlvkwxf2mtnjhrx0z3wj9a4ker204xsyqgvxt79
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRDYxZzd3MFhCU2hLNE5J
            dk41WkNyWW9Sb2RuNDNaTjZBUEZGV0JtU1JBCmZoMk0ybnpnK0FXWFBLbVMrZWVR
            b0J3bFRCVXFBNzZxM0xzbUdJazFubkUKLS0tIDh0S3NNZDFRWE11bTdXVFNDZi9l
            Q3dUdzhacEM4Rm9WbzZkMm8vVWluc1kKXEQh9jm71ZlNk/rHlpsnxh1cjLlP0Ye9
            s/w/0hfTxspTitpl+FAAkCw+TSWsekTQHg2iEQjOz5mDbOCOn2zk8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-23T20:08:37Z"
    mac: ENC[AES256_GCM,data:hYTbOLSPfQHPo6OPbs9W7mTsMeeztNxxdbAQtDs1AVstBpEedr4VPUbymkIEDcySx3Rl+2un5MMoHFN0On/EdjjQolZpd8fHWLNxdZWqgisAPh2yKQLEBzcGz4Diw9N0c5BpKMKFqp5j6f6zawR2HYoBz5fIBkhJBoagNLejmVE=,iv:+XXsBarau4YDG4SehuZWor58Qb4ykDOFQZ2YlSE8mAo=,tag:pzDENp4h8rOgbXBUQm4yjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
