apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:pGct5ivHB6HR04t/gl6o6K7sjPcNfqWt80+H/Fwq1IVN3XOo,iv:GKWT5KQZSvZfbqfr3uBhskIdeqdVsbmxrOXGfz3e0ps=,tag:d7rAv2xkaJazX0u9W44oHA==,type:str]
    credentials.json: ENC[AES256_GCM,data:gXoX/R8FZz/NT8Ii+JHb6+vuPIimDxQxwr3W24I7SG7N5DxELBEjNDv9hOiyN2umySO6nK94zn2svLIuTpLb4kSH2MZXc+Ktxta3CNRvGrnr2xM0d5JH+t4u1KdNfYhYrij9j1Vg2Y1ONL8LiNFBZqq3iKs2voWt2cEtzi23yHxSxxQgFnlhEqjctGWU8VxUDCNGb3wwlKrN4QY7yk4nppncqlHnCEyjxzjfuRbTJA==,iv:uI0cUIIKb2XOky8zP60OQ8YIzW0F0YT2ZqXtb20ynHQ=,tag:NAIjij5WydNkyPR0TjMs5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lm9yj3lcn9xy8qzwvhs0fr77vzxdzggqr3te7307dxx8eztsay4sewphmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUWpUeFZWbGlSTDlya3BW
            YVZ0cTQ3ZjFsdmZ5L2Fyc1hoM1Z5enV1YjE0Cm5BWUExcFVzQ3VkVFN0T1dmRWJt
            dW82TWxmbnk3dHlQWkMvTkk0MFRBM3MKLS0tIGhxQlJkNjMzVzBFSDFIeElnRWRt
            YWdJeFpXRlBicm1Jc2w4T0RzZWFOT2cK8NLDmKr9V0dA/0s1Ur+K3JVaRSvhv3qN
            GfEES5X0Bwz9xZlcehJ90aJIoYW445GYYAllJ9ULQaJOAdHCJIVyvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-26T04:14:03Z"
    mac: ENC[AES256_GCM,data:1XZoALUcqh2EB7O044BoKRd2Bcoo66OIEx5Bc3XC8qP+Nf2XJkepCJquPxP4UiH6CuzIEkFcLD7AuJsa0W8Aza8z3LXOXSXKnFFu1DYkBpUrKAvttnijnMsuD0u8e1hs75MG+7QnlWXJR6txEuRxG6eMTpYRZaO8LsIQPDCsM8w=,iv:f/cUlExI4EBEset9f0KPQ5W2OPz3lUyPIoIPZkgPRZk=,tag:2gZawuiULLQi5piKu+Z/+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
