apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ZGICXWxrvKJAAdZlKKtHxO/Vn98a5CLWxLG8FVUcegFfDLdUySpnBA==,iv:0hqc8aYpg1S4QaVLA/HDRrfN94aGCrvfZiMvPWHvmDU=,tag:MjuKX5S5jFsPVgnNvYR0ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zeeh6dv2dnu0de6xd2zlvkwxf2mtnjhrx0z3wj9a4ker204xsyqgvxt79
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SVEzUHJKRXB6c1hvcjcz
            b2tPWFdYdnJoRHQxVEViOERoSHFsTFY0aEVJCmprNU9rbHZTTWJTSFVieVQ5VVI3
            azFmakV6QW94Tm9SUERVSkY4akZmNTgKLS0tIE5QUHhDejR5Y1JSRkJGWXF1SXZN
            MEtYa2hmZko3Q04wY3A1R2ZxRkl5dTAKVwGKTA7CDLLyMNRSJzarB/Al+z+deVJa
            uJOcH5zMKuwnug4OZNBmU7xRLpfOOrXPHz26YUCNyKUzb7cvgqqJwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-25T17:34:37Z"
    mac: ENC[AES256_GCM,data:6cajBKWB07rKdtgXrDNevBzr+iKv394PiFtb6ip93c3XXiac0Xmvyph/n4/ODXC5qg03qnkBhiiZqwwVsDzwlskiGQoni68d1WAJFft+aHgbhMVHmDk/Io2xXAViGxKshblOLXSYaWToGscoZFe3F8gF47Ir5k1muFr5WS22y5k=,iv:WxqzwxHWCGc5yZlrgV6/6dUcbfWP0O1RLqOPQ0G3VHU=,tag:nIRKD/kupw532HLSXgCNpQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
