apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:28HWjLNp1p5RBLsP7ZdLddVZupMu9ZdPUvkzraOfYgPUSURi3xYuRg==,iv:UL9WCwZkLao4SHvjzhA80b6AEsMYpwjS4VoBEbXbGsM=,tag:XVXpCfjyL1FcvsLA9lLkyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zeeh6dv2dnu0de6xd2zlvkwxf2mtnjhrx0z3wj9a4ker204xsyqgvxt79
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBud2I2bUExVTU5ZUxScnRB
            ZVpnSU5zUUJacTNhZ2RmMkR5VERpSHNlWUFnCis5SnhwYmVYYThFN2czMlV5UUN1
            YkZtM203UjE1NWdVc05vMkNBNWdDcGcKLS0tIHJvT2RDUlNIU1RhbHNhY2pPKzJO
            cjlOU1RWZkZoak9RMWZsWHpqbnU5YzAKFIkAAZumZXIcl4IL5FUBa6mDaYfDSLOx
            8//ulgrh/x5kwtTpEvac8b5y1VMpPxr605NVTgDIqayBcFliikMfaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-23T20:08:37Z"
    mac: ENC[AES256_GCM,data:k3n7XFqBSPK/tlKZ/+ugQJHqr/Vy/hABLizqI3e0iF8RwUqwmjRr/T/9NmupCR+Gfp+JQActxAZxsuSoe/gD4ticZkYFvIp/LsyxYMp4WexvTIVpooxCU5tig5QlqJMAkfuN0U2HlkOujv2f24uTyml9zv4Y+ibD+od+iKeerII=,iv:Y5mkyq0Fz6mLSpLXjsKx/6q4Cyi1dgvj/DiAf96G7rc=,tag:1t6+2WMofIKMqXcas0hexQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
