apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:8TnBW2k9ewdgbdF7Kx04XdB1V0ODUgQtKAy4XqJtgR6v1CrvQO4IRGfJlMgsBW39MW6MCt7mHOYnMPsplqoWX7+boII7grAGc4t1+vGeCkl+CE6ce88p7HxEHgdYew==,iv:wMxmHNSksY9XU9JzGiPHp4CO72XlvoHVjnCyh37JX70=,tag:ds6uWZU8Du6bVO7b3mDdQA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:mytixoQWMdVIRMKD,iv:SPKkbXTJdL34CSXxzEQaKLyA5aYj495RUnDlhqtUqf4=,tag:+B2cwUT2sQ70ZeZSNCQb4g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:YzfzLVV4teaVtAsxpnN+0x0/KFk1,iv:VTcxPB+909IvNizl9aaR+0qIwJu4eygNmmX9sxS7N20=,tag:xBaIQOQSWiyR557UlL3/0Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:RwPvvY6M/RakRFrue05lH9J7TlL/q9nBAL38DoRibbnX3UWN,iv:b8Zhwzj/IaaitOiuogMHp5QZEm0zdFbgRsUQIOEP7qw=,tag:lAyzCfb3jO48MU9O6OP2rw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zeeh6dv2dnu0de6xd2zlvkwxf2mtnjhrx0z3wj9a4ker204xsyqgvxt79
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUWVuZTBHKy85WUluSE9B
            alEvUTIzYXMycHNGYlRCdGR6WGxGNjNaL1E0ClVzSGwxdDJJdDFGdmdHcHlUOFFW
            SE9yLzZsa3RKRWh0Sm5TZU1BbkRXREkKLS0tIFB2S2YyT2hRanNvR0Fzb0czOGRz
            Y1dZbXBDZG13REVyaDZ1RGFJREZGclEKpurba3zV8JXYBDQ6ps5XGtdP9TvHNovr
            lAQ0CjrOyDP2Z0br7H0j2cbTOov1Fsosyo8pNgwsYl5PJsTO+4uiiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-23T20:08:37Z"
    mac: ENC[AES256_GCM,data:9TScjpXzlVmqqEGi77AcRZ/f3+xWMeiYHcgT0Ry24dGgBadTPm0vs3THUJd0FmjTB35AhYWpSCivO3Q+5M+cR4z5N3JxJWiXNB9mlfbRaP7EvlenUtHKNXobqMNj0IqURA+bv5IQSRcZQB7cXbnA+x2i9M4Nhl+6bzmRpafBThQ=,iv:wUVYNw4zVWKhMtWEKbCtyDto7AeZa5JBqQV26MZ89hY=,tag:x4R12EDgsu/KTnOxSGDvIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
