apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:oznfY4UI9FlwCzn0dcVDM/xFg2J6nsAe,iv:vWCoi0l4geV23iEdhSXzfXxjNXxKjDCRlIHokMHnTu0=,tag:+B0/zx7BVpAh2DAMMqqsfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zeeh6dv2dnu0de6xd2zlvkwxf2mtnjhrx0z3wj9a4ker204xsyqgvxt79
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENUd6bVlNcXduQzZsTUZQ
            UmJrbnk4RENIWGlKZjJGOThXTzBIQ040dlJzClhBUmFmT1ZnOHRXa0wzVzhmbU5H
            N1NySGorblNUZ3REOGdEZWgwck9ZRFkKLS0tIHpUa3RxdHgxOElKbEdmWVgxYXpm
            d1VzbE85Y1kzNlNDamJzclZBNmRtL1kKICaRCqOafAlndflKtfduqraZnKWNBx2Y
            GIktW7C78ljxONVEmSDZKmSS9XFp1xvfOtPSoOIsjfs44hrG1RhoiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-23T18:49:09Z"
    mac: ENC[AES256_GCM,data:FrUZlUhB2vif4tpyLc0JumxZ9ZnNGCiIGNtt6VZwckuKCcn0cm8yk1XalH+BXOeKO20KYXwzY6VsrZ16dKrBfCgiSgJWesAgHW9hBsD5JcaI0RZrfryIG8odUiImovyUT8MrIkk3U9nntaHVogZhlZMIDVbola3tcysXTTwvYHs=,iv:ZyOpUUu3Zn68xmZR5P4mscDDp5U7/jbu5DyO1P2GnsA=,tag:wunMHoqJDwj/Y/Jm80XcqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
