apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:glfKoYF9n07bMBdTezwEb1tK3VfWUNHdO//qEj6BnZxne8xSoi2nWA==,iv:9H9fPjAx1jyaDZeb2dnuWHcdCSjt2B869t+Af9wyZ9A=,tag:4c3N7wfmtRhdXrH2619Fvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lm9yj3lcn9xy8qzwvhs0fr77vzxdzggqr3te7307dxx8eztsay4sewphmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYWZMQ0wvVmNKeTZEL0JZ
            UnBvM0gvM1YvQXk5VzFKYy9TMXNDN3l0SzFRCkNrKzRwQUFWcXljVExiT3k3eU84
            U0FJWmRCbUp3dHAzd3krM3dpY2JQOU0KLS0tIEF3VEsrVlYyYW9MVm1ia2RzUXhE
            OXdDN2luaVYrbnRhUEZyQTdqK05kdGcKY1GARIny62HuyYy8cj3SheZglaF8Dv1x
            xImGeQ+HjsaNTd1Al28l5cgn8tk9ihyjZdjBDFJF8cto4gg4eTCF/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-26T04:14:03Z"
    mac: ENC[AES256_GCM,data:dURw8LAq5dVF6fUNj0dBFztoryvpIk8Nco9aqlbG5JO/5N1bGdGxaP5G5pqdVE3BF97VW5EOwP2fMXQYLxtE/vIq6XfWO3TvkDmgBgPlmx7lBAY+Ikxgwh3kroM731ywugz5cVe9PCf0ysJq/zvq/zIdZcOZFnK1eANNAlR5uQA=,iv:cu7s17J06dpBXX9LwXUZoqy0m5Jkk2LfD/jmLqIRcS8=,tag:a7gjGYPk+yQ+4IB5aMjq6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
