apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:7nxDABW8k9Zz+v4ZDVQKIOTQDuLdMA1XwVsrJvir2mzLbWjnLVAWcg==,iv:bOuWtE+J+4XqbYeZbu8D4T+16FZTlEODsSgdyj5x10w=,tag:ZH9/tjCZpITKn2mOKUooAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lm9yj3lcn9xy8qzwvhs0fr77vzxdzggqr3te7307dxx8eztsay4sewphmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTeGEzYm1oWm5CNDM1eXYy
            U1VaQjBKM205M1BnWHF1WHYvOUMxenZCenhvClpHTmQrRy81YU1uUkpPMHRRK05r
            WVhuRWpLU0wzQmFGY1JDVWFYN1piS28KLS0tIFN6R0RYb3Yvc0NNY3ljbE9BeWdH
            TDhBTTJ4dDhUdytCU2NuODV2Mm84MDAKKt/0R2/Reh2v5qfaAcFZ1KPiMM18Pa3X
            39aMfU7sl9T7/dUfrnKMcOmwdsJIT77VID60RW11nzO2/0ql/LMEjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-07T17:58:09Z"
    mac: ENC[AES256_GCM,data:xvA10YDkexbFmDhVXsifDgqkeG0j83MJhm6pXVYGdQ5V55aLzOmPHy3zK3523ikkR3IRpMDpc41mKHNPL1NkfVPZBo9NLDNLF2VPv6FkXRZRuAftiAsYSS987JowXmxexV9+VPVsqkIQ06hQdXYfMmMp9eqAwTa0ES430KseogA=,iv:q+On0THSPjquAKBBfVrLwF2LLLcDli8Hx9a4gQJPjJc=,tag:MXYlri6Pbyl8B0y0yAu84A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
